---
- name: Check Software Installation Playbook
  hosts: vps1, vps2, vps3
  gather_facts: false

  tasks:
    - name: Check Python 3.13.2 Installation
      command: python3 --version
      register: python_check
      ignore_errors: true

    - name: Check Kustomize Installation
      command: kustomize version
      register: kustomize_check
      ignore_errors: true

    - name: Check PyYAML Installation
      command: python3 -c "import yaml"
      register: pyyaml_check
      ignore_errors: true

    - name: Check pip3 Installation
      command: pip3 --version
      register: pip3_check
      ignore_errors: true

    - name: Check Helm Installation
      command: helm version
      register: helm_check
      ignore_errors: true

    - name: Display Check Results
      debug:
        msg: |
          Python 3.13.2: {{ "INSTALLED" if python_check.rc == 0 else "NOT INSTALLED" }}
          Kustomize: {{ "INSTALLED" if kustomize_check.rc == 0 else "NOT INSTALLED" }}
          PyYAML: {{ "INSTALLED" if pyyaml_check.rc == 0 else "NOT INSTALLED" }}
          pip3: {{ "INSTALLED" if pip3_check.rc == 0 else "NOT INSTALLED" }}
          Helm: {{ "INSTALLED" if helm_check.rc == 0 else "NOT INSTALLED" }}
